import * as functionsV1 from "firebase-functions/v1";
import * as admin from "firebase-admin";
import { requireAdmin } from "./auth";
import { generateSeoContentCore } from "./seo";

/**
 * Model pages that make themselves.
 *
 * There are 3,684 models in the database and 230 landing pages, and each of
 * those pages is a search anybody actually types — "samsung galaxy s23 skins".
 * The machinery to write one has existed for a while; what has never existed
 * is anything that notices a model has no page. So a gap opened while the site
 * was down, and it would open again every month as new phones launch, because
 * filling it depended on somebody remembering.
 *
 * This runs nightly, newest models first: any new phone gets its page within a
 * day of being added, and the backlog is chipped at from the front. The daily
 * cap is what stops one night's run spending a month's OpenAI budget.
 *
 * Pages are made unpublished unless SEO_AUTO_PUBLISH says otherwise, and the
 * morning digest reports how many are waiting — thin or wrong pages at scale
 * are worse for a site than missing ones, so a person sees them first.
 */

const SETTINGS = {
  perDay: "SEO_AUTO_PAGES_PER_DAY",
  autoPublish: "SEO_AUTO_PUBLISH",
};

async function setting(db: admin.firestore.Firestore, key: string): Promise<any> {
  const snap = await db.collection("settings").doc(key).get();
  return snap.exists ? (snap.data() as any)?.value : undefined;
}

/** "Samsung" + "Galaxy S23" → "samsung-galaxy-s23-skins", as the admin screen builds it. */
export const modelSlug = (brand: string, model: string) =>
  `${`${brand} ${model}`.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")}-skins`;

/**
 * One complete sentence, at most 160 characters.
 *
 * The same rules the admin screen applies, because a description cut off
 * mid-word is what Google shows the whole world. Kept in step with
 * src/pages/admin/seo-pages/auto-generate.tsx.
 */
export function metaDescriptionFrom(html: string): string {
  const firstParagraph = html.match(/<p>(.*?)<\/p>/)?.[1] || "";
  const clean = firstParagraph.replace(/<[^>]*>/g, "").trim();
  let sentence = (clean.match(/^[^.!?]+[.!?]/) || [clean])[0].trim();
  if (sentence.length <= 160) return sentence;

  sentence = sentence.replace(/\s*\([^)]*\)\s*/g, " ");
  if (sentence.length > 160) {
    sentence = sentence.split(",")[0].trim();
    if (!/[.!?]$/.test(sentence)) sentence += ".";
  }
  if (sentence.length > 160) {
    let cut = sentence.slice(0, 157);
    const space = cut.lastIndexOf(" ");
    if (space > 100) cut = cut.slice(0, space);
    cut = cut.replace(/[,;:]$/, "");
    if (!/[.!?]$/.test(cut)) cut += ".";
    sentence = cut;
  }
  return sentence.replace(/\s+/g, " ").trim();
}

export interface Coverage {
  models: number;
  brands: number;
  pages: number;
  modelsWithPage: number;
  modelsMissing: number;
  brandsMissing: string[];
  waitingToPublish: number;
}

/** What has a page and what does not — the number nobody could see. */
export async function seoCoverage(db: admin.firestore.Firestore): Promise<Coverage> {
  const [modelSnap, pageSnap] = await Promise.all([
    db.collection("supportedModels").get(),
    db.collection("seoPages").get(),
  ]);

  const slugs = new Set(pageSnap.docs.map((d) => String((d.data() as any).slug || "")));
  const waitingToPublish = pageSnap.docs.filter(
    (d) => (d.data() as any).autoGenerated === true && (d.data() as any).isPublished !== true
  ).length;

  const brands = new Set<string>();
  let withPage = 0;
  for (const d of modelSnap.docs) {
    const m = d.data() as any;
    if (m.isActive === false) continue;
    const brand = String(m.brandName || "").trim();
    if (brand) brands.add(brand);
    if (slugs.has(modelSlug(brand, String(m.modelName || "")))) withPage++;
  }

  const brandsMissing = [...brands].filter(
    (b) => !slugs.has(`${b.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")}-skins`)
  );

  const activeModels = modelSnap.docs.filter((d) => (d.data() as any).isActive !== false).length;
  return {
    models: activeModels,
    brands: brands.size,
    pages: pageSnap.size,
    modelsWithPage: withPage,
    modelsMissing: activeModels - withPage,
    brandsMissing,
    waitingToPublish,
  };
}

export interface FillResult {
  considered: number;
  created: number;
  failed: number;
  published: boolean;
  slugs: string[];
  errors: string[];
}

/**
 * Writes pages for the models that have none, newest first.
 *
 * Newest first on purpose: a phone added today is the one people are searching
 * for today, and a page that arrives six months late has already missed its
 * traffic.
 */
export async function fillMissingSeoPages(
  db: admin.firestore.Firestore,
  opts: { limit?: number; dryRun?: boolean } = {}
): Promise<FillResult> {
  const perDay = Number(opts.limit ?? (await setting(db, SETTINGS.perDay)) ?? 0);
  const out: FillResult = { considered: 0, created: 0, failed: 0, published: false, slugs: [], errors: [] };
  if (!(perDay > 0)) return out;

  const autoPublish = (await setting(db, SETTINGS.autoPublish)) === true;
  out.published = autoPublish;

  const [modelSnap, pageSnap, templateSnap] = await Promise.all([
    db.collection("supportedModels").get(),
    db.collection("seoPages").get(),
    db.collection("seoPageTemplates").get(),
  ]);

  const slugs = new Set(pageSnap.docs.map((d) => String((d.data() as any).slug || "")));
  const deviceTemplate = templateSnap.docs
    .map((d) => d.data() as any)
    .find((t) => t.pageType === "device");

  const missing = modelSnap.docs
    .map((d) => ({ id: d.id, ...(d.data() as any) }))
    .filter((m) => m.isActive !== false && m.brandName && m.modelName)
    .filter((m) => !slugs.has(modelSlug(String(m.brandName), String(m.modelName))))
    .sort((a, b) => (Number(b._creationTime || b.createdAt) || 0) - (Number(a._creationTime || a.createdAt) || 0))
    .slice(0, perDay);

  out.considered = missing.length;
  if (opts.dryRun) {
    out.slugs = missing.map((m) => modelSlug(String(m.brandName), String(m.modelName)));
    return out;
  }

  for (const m of missing) {
    const device = `${m.brandName} ${m.modelName}`.trim();
    const slug = modelSlug(String(m.brandName), String(m.modelName));
    try {
      const ai = await generateSeoContentCore({
        pageType: "device",
        keywords: [device],
        deviceCategory: device,
        brandName: String(m.brandName),
      });
      if (!ai.contentHTML) throw new Error("no content came back");

      const title = `${device} Skins & Wraps`;
      await db.collection("seoPages").add({
        pageType: "device",
        slug,
        h1Heading: title,
        metaTitle: title,
        metaDescription: metaDescriptionFrom(ai.contentHTML),
        contentHTML: ai.contentHTML,
        faqs: ai.faqs || [],
        keywords: [device],
        imageAltTexts: ai.imageAltTexts || [],
        filterConfig: { brand: String(m.brandName), model: String(m.modelName) },
        ...(deviceTemplate?.layoutConfig?.sections
          ? { layoutOverrides: { sections: deviceTemplate.layoutConfig.sections } }
          : {}),
        isPublished: autoPublish,
        // Stamped, so these can be found, reviewed and — if the writing turns
        // out wrong — removed as a group.
        autoGenerated: true,
        autoGeneratedAt: Date.now(),
        supportedModelId: m.id,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      });
      out.created++;
      out.slugs.push(slug);
    } catch (e: any) {
      out.failed++;
      out.errors.push(`${slug}: ${e?.message || e}`);
      console.error("seoAuto: page failed", { slug, error: e?.message || e });
    }
  }

  console.log("fillMissingSeoPages", { created: out.created, failed: out.failed, autoPublish });
  return out;
}

/** 20:00 UTC is 01:30 in Agra — before the nightly rebuild picks the pages up. */
export const seoAutoPages = functionsV1
  .runWith({ memory: "512MB", timeoutSeconds: 540 })
  .pubsub.schedule("0 20 * * *")
  .timeZone("UTC")
  .onRun(async () => {
    await fillMissingSeoPages(admin.firestore());
    return null;
  });

/** The coverage figures and a run, on demand, for the admin screen. */
export const runSeoAutoPages = functionsV1
  .runWith({ memory: "512MB", timeoutSeconds: 540 })
  .https.onCall(async (data: any, context: any) => {
    await requireAdmin(context);
    const db = admin.firestore();
    if (data?.coverageOnly === true) {
      const c = await seoCoverage(db);
      return {
        success: true,
        coverage: c,
        message: `${c.modelsWithPage} of ${c.models} models have a page — ${c.modelsMissing} do not`
          + (c.waitingToPublish ? `, and ${c.waitingToPublish} auto-written pages are waiting to be published` : ""),
      };
    }
    const limit = data?.limit === undefined ? undefined : Number(data.limit);
    const out = await fillMissingSeoPages(db, { limit, dryRun: data?.dryRun === true });
    if (!out.considered) {
      return { ...out, message: "Nothing to write — either every model has a page, or the daily cap is 0." };
    }
    return {
      ...out,
      message: data?.dryRun === true
        ? `${out.considered} models would get a page: ${out.slugs.slice(0, 5).join(", ")}…`
        : `${out.created} pages written${out.failed ? `, ${out.failed} failed` : ""}`
          + (out.published ? " and published" : " — waiting to be published"),
    };
  });
